# Build Docker image with CI/CD and push to the GitLab registry.
image:
  name: gcr.io/kaniko-project/executor:debug
  entrypoint: [""]
before_script:
  - wget http://eoelab.org:1024/index.php/s/XHeP7K3ZAHPHymM/download/eoelab.org.crt
  - mv eoelab.org.crt /kaniko/ssl/certs/additional-ca-cert-bundle.crt
base-build:
  stage: build
  needs: []
  script:
    - cd base
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:base"
steam-build:
  stage: build
  needs: [base-build]
  script:
    - cd steam
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:steam"
7dtd-build:
  stage: build
  needs: [steam-build]
  script:
    - cd 7dtd
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:7dtd"
satisfactory-build:
  stage: build
  needs: [steam-build]
  script:
    - cd satisfactory
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:satisfactory"
java-8-build:
  stage: build
  needs: [base-build]
  script:
    - cd Minecraft/java-8
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:java-8"
java-11-build:
  stage: build
  needs: [base-build]
  script:
    - cd Minecraft/java-11
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:java-11"
java-17-build:
  stage: build
  needs: [base-build]
  script:
    - cd Minecraft/java-17
    - /kaniko/executor
      --context ./
      --dockerfile "Dockerfile"
      --cache=true
      --cache-copy-layers=true
      --cache-run-layers=true
      --cache-repo "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/cache"
      --destination "eoelab.org:1032/build-image-stacks/gameserver-image-stacks/gameserver:java-17"
